"""
utils/file_utils.py — File Classification Utilities
Placement: backend/utils/file_utils.py
"""
from pathlib import Path

SKIP_DIRS: frozenset[str] = frozenset({
    ".git", ".svn", ".hg",
    "node_modules", ".pnpm-store", ".yarn",
    "venv", ".venv", "env", ".env",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "site-packages",
    "dist", "build", ".next", ".nuxt", ".svelte-kit",
    "out", "output", "target", "bin", "obj",
    ".idea", ".vscode", ".vs",
    ".DS_Store", "Thumbs.db",
    "coverage", ".coverage", "htmlcov", "reports",
    "_site", "site", ".docusaurus",
})

SKIP_EXTENSIONS: frozenset[str] = frozenset({
    ".exe", ".dll", ".so", ".dylib", ".bin", ".class", ".pyc", ".pyo",
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".rar", ".7z", ".whl",
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp",
    ".bmp", ".tiff", ".psd",
    ".ttf", ".woff", ".woff2", ".eot", ".otf",
    ".mp4", ".mp3", ".wav", ".avi", ".mov", ".webm",
    ".pdf", ".docx", ".xlsx", ".pptx",
    ".db", ".sqlite", ".sqlite3",
    ".min.js", ".min.css", ".map",
    ".pt", ".pth", ".onnx", ".pkl", ".h5",
    ".csv", ".parquet", ".arrow", ".npy", ".npz",
})

SKIP_FILENAMES: frozenset[str] = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "Pipfile.lock", "Gemfile.lock",
    "Cargo.lock", "composer.lock",
    ".DS_Store", "Thumbs.db",
    ".gitignore", ".gitattributes", ".editorconfig",
    ".prettierignore", ".eslintignore",
    "CHANGELOG.md", "CHANGES.md", "HISTORY.md",
    "LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING",
})

EXTENSION_TO_LANGUAGE: dict[str, str] = {
    ".py": "Python", ".js": "JavaScript", ".ts": "TypeScript",
    ".jsx": "React (JSX)", ".tsx": "React (TSX)",
    ".go": "Go", ".rs": "Rust", ".java": "Java",
    ".kt": "Kotlin", ".swift": "Swift",
    ".cpp": "C++", ".c": "C", ".cs": "C#",
    ".rb": "Ruby", ".php": "PHP", ".scala": "Scala",
    ".ex": "Elixir", ".exs": "Elixir",
    ".hs": "Haskell", ".lua": "Lua", ".r": "R",
    ".sh": "Shell", ".bash": "Bash", ".zsh": "Zsh",
    ".fish": "Fish", ".ps1": "PowerShell",
    ".html": "HTML", ".css": "CSS", ".scss": "SCSS",
    ".sass": "Sass", ".less": "Less",
    ".vue": "Vue", ".svelte": "Svelte",
    ".sql": "SQL", ".md": "Markdown",
    ".yaml": "YAML", ".yml": "YAML",
    ".toml": "TOML", ".json": "JSON",
    ".xml": "XML", ".proto": "Protocol Buffers",
    ".graphql": "GraphQL", ".tf": "Terraform", ".hcl": "HCL",
}

def get_language(path: Path) -> str:
    name = path.name.lower()
    if name == "dockerfile":
        return "Dockerfile"
    if name == "makefile":
        return "Makefile"
    if name == "rakefile":
        return "Ruby"
    return EXTENSION_TO_LANGUAGE.get(path.suffix.lower(), "Unknown")

_ENTRY_FILENAMES: frozenset[str] = frozenset({
    "main.py", "app.py", "run.py", "server.py", "wsgi.py", "asgi.py",
    "index.js", "index.ts", "index.jsx", "index.tsx",
    "main.js",  "main.ts",  "main.jsx",  "main.tsx",
    "app.js",   "app.ts",
    "manage.py", "application.py",
})

_CONFIG_FILENAMES: frozenset[str] = frozenset({
    "requirements.txt", "setup.py", "setup.cfg", "pyproject.toml",
    "package.json", "tsconfig.json", "jsconfig.json",
    "vite.config.js", "vite.config.ts",
    "webpack.config.js", "rollup.config.js",
    "next.config.js", "nuxt.config.js",
    "tailwind.config.js", "tailwind.config.ts",
    "jest.config.js", "jest.config.ts",
    "babel.config.js", ".babelrc",
    "dockerfile", "docker-compose.yml", "docker-compose.yaml",
    ".env.example", ".env.template",
    "makefile", "justfile", "cargo.toml",
    "go.mod", "pom.xml", "build.gradle",
    "gemfile", "composer.json",
})

def get_file_role(path: Path) -> str:
    name = path.name.lower()
    stem = path.stem.lower()
    ext = path.suffix.lower()
    if name in _ENTRY_FILENAMES:
        return "entry"
    if name in _CONFIG_FILENAMES:
        return "config"
    if (
        stem.startswith("test_")
        or stem.endswith("_test")
        or stem.startswith("spec_")
        or stem.endswith("_spec")
        or "test" in stem
        or "/tests/" in str(path)
        or "/test/" in str(path)
        or "/spec/" in str(path)
    ):
        return "test"
    if ext == ".md" or name in {"readme", "readme.txt"}:
        return "docs"
    if ext in {".jsx", ".tsx", ".vue", ".svelte"}:
        return "ui"
    return "core"

_ROLE_SCORES: dict[str, int] = {
    "entry": 100, "core": 60, "ui": 50,
    "config": 40, "test": 20, "docs": 10,
}
_EXTENSION_BONUSES: dict[str, int] = {
    ".py": 10, ".js": 10, ".ts": 10, ".jsx": 8, ".tsx": 8,
    ".go": 10, ".rs": 10, ".java": 10,
}
_GENERATED_INDICATORS = ("migration", ".generated.", "autogenerated", "generated_by")

def score_file(path: Path, file_size_bytes: int = 0) -> int:
    role = get_file_role(path)
    score = _ROLE_SCORES.get(role, 30)
    score += _EXTENSION_BONUSES.get(path.suffix.lower(), 0)
    if file_size_bytes > 50_000:
        score -= 20
    if file_size_bytes > 200_000:
        score -= 40
    name_lower = path.name.lower()
    if any(ind in name_lower for ind in _GENERATED_INDICATORS):
        score -= 30
    return max(score, 0)

def should_skip_dir(dir_name: str) -> bool:
    return dir_name in SKIP_DIRS or dir_name.startswith(".")

def should_skip_file(path: Path) -> bool:
    name = path.name
    ext = path.suffix.lower()
    if name in SKIP_FILENAMES:
        return True
    if ext in SKIP_EXTENSIONS:
        return True
    if name.startswith(".") and name not in {".env.example", ".env.template", ".flake8", ".pylintrc"}:
        return True
    return False

def is_text_file(path: Path, max_check_bytes: int = 8192) -> bool:
    try:
        with open(path, "rb") as f:
            chunk = f.read(max_check_bytes)
        non_printable = sum(1 for b in chunk if b < 9 or (13 < b < 32) or b == 127)
        return non_printable / max(len(chunk), 1) < 0.30
    except (OSError, PermissionError):
        return False